### ISSUE TITLE
Getting Google contacts fail

### ISSUE THREAD

**Issue by adidalal** [pkoenig10/sink#1]
Ran across your project while looking for a faster way to update my Google Contact photos. Unfortunately, it doesn't seem to be working for me.

OAuth authentication works (and "feed" is retrieved, but somewhere along the way parsing seems to be broken)

``` python
(venv)[~/Downloads/sink-master] > python sink.py update
Getting Google contacts...
Traceback (most recent call last):
  File "sink.py", line 411, in <module>
    main()
  File "sink.py", line 372, in main
    sink = Sink(shelf)
  File "sink.py", line 234, in __init__
    self.contacts = self.google.get_contacts()
  File "sink.py", line 186, in get_contacts
    if contact.name.full_name:
AttributeError: 'NoneType' object has no attribute 'full_name'
```

Pip info:

```
beautifulsoup4 (4.4.1)
fuzzywuzzy (0.8.0)
gdata (2.0.18)
pip (7.1.2)
setuptools (18.2)
wheel (0.24.0)
```

Python info:

```
Python 2.7.10
```

I'm thinking it may be a library version issue.
Would you mind comparing library versions/taking a look?

**Comment by pkoenig10** [comment]
The Google Contacts API is returning a name field of None for some of your contacts (maybe you have not entered a name for those contacts).  Sink now checks to make sure this field is not None and will ignore any contacts where this is the case.
