### ISSUE TITLE
Problem with special characters – ø

### ISSUE THREAD

**Issue by NoLooseEnds** [pkoenig10/sink#10]
Hi thanks, for this!

I'm experiencing a crash when a name is containing "ø" (and probably other unusual chars as well).

- The name is not matched properly, even though it is spelled exactly the same. 
- The name does not show up in the list of alternatives
- When searching for name I get the crash below.

```
> Namendingwithø
Traceback (most recent call last):
  File "sink.py", line 425, in <module>
    main()
  File "sink.py", line 388, in main
    sink.update(args.update_ignored, args.auto_only, args.score_threshold, args.match_limit, args.retries)
  File "sink.py", line 242, in update
    self._update_links(update_ignored, auto_only, score_threshold, match_limit)
  File "sink.py", line 302, in _update_links
    self._get_link(contact_url, score_threshold, match_limit, True)
  File "sink.py", line 338, in _get_link
    matches = self._get_matches(name, match_limit)
  File "sink.py", line 364, in _get_matches
    return process.extract(name, self.friends, scorer=fuzz.UWRatio, limit=match_limit)
  File "/Library/Python/2.7/site-packages/fuzzywuzzy/process.py", line 193, in extract
    return heapq.nlargest(limit, sl, key=lambda i: i[1]) if limit is not None else \
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/heapq.py", line 470, in nlargest
    result = _nlargest(n, it)
  File "/Library/Python/2.7/site-packages/fuzzywuzzy/process.py", line 103, in extractWithoutOrder
    processed_query = processor(query)
  File "/Library/Python/2.7/site-packages/fuzzywuzzy/utils.py", line 89, in full_process
    string_out = StringProcessor.replace_non_letters_non_numbers_with_whitespace(s)
  File "/Library/Python/2.7/site-packages/fuzzywuzzy/string_processing.py", line 26, in replace_non_letters_non_numbers_with_whitespace
    return cls.regex.sub(" ", a_string)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5: ordinal not in range(128)
```

I also had a problem with searching up a name "Firstname A. B. Lastname". No crash, but it does not show up as an alternative even if the search term is identical (copy/paste) from FB

**Comment by pkoenig10** [comment]
Regarding the issue searching a name, did you try searching just "Firstname" or just "Lastname"? That might get the result you are looking for to show up.

You can also try to increase the number of matches shown using the `--matches` option (see the documentation for more information).

If it still does not work, your best bet is probably to debug by printing out the retrieved list of friends.

**Comment by NoLooseEnds** [comment]
Thanks! I'll give it a go later today. Appreciate the quick answer. :)

**Comment by NoLooseEnds** [comment]
I'm testing now, and it no longer crashes, but it does not list this particular person. Her name ends on "ø".

**Comment by pkoenig10** [comment]
Can you try printing out the retrieved list of friends and see if her name appears there?
https://github.com/pkoenig10/sink/blob/e1e1e820fc76ed3f5542dfa79f56d7006672842b/sink.py#L239

**Comment by NoLooseEnds** [comment]
Thanks for the quick reply. How do I go about doing that? I'm pretty newbie regarding python (other than executing a script here and there).

**Comment by pkoenig10** [comment]
`self.friends` is just a dictionary mapping friend profile URLs to their name. You can add the following line after the line I linked above to print out this entire mapping:
```
print self.friends
```

You can then search that output for your friend's name and see if appears as you expect.

**Comment by NoLooseEnds** [comment]
Thanks. Will try tonight. 

It's a couple of friends that I can't see. Could their privacy settings be kicking in? Or if they have a custom URL? We are clearly friends on FB.

**Comment by NoLooseEnds** [comment]
I tested now, and the two I have a problem with does not show up. 

- One of them has a custom url that does not resemble her name at all. This is the on with an "ø" at the end of her last name.
- The other has Firstname A. B. Lastname, but has a URL of fb.com/firstname.lastname

I have full access to their profile, photos, etc. (and afaik they have no reason to block me).

Seen this before?

**Comment by pkoenig10** [comment]
The URLs (keys in the dictionary) are irrelevant. The fuzzy matching is done against the friends names (values in the dictionary). See [here](https://github.com/seatgeek/fuzzywuzzy/blob/0.16.0/fuzzywuzzy/process.py#L50-L53).

If your friend's names exist in the dictionary as expected, then I'm not sure what the issue is. You can try manually playing around with fuzzywuzzy to see if you can reproduce the seemingly incorrect behavior.

**Comment by pkoenig10** [comment]
Your friend infomation is just scraped from the basic mobile site (https://mbasic.facebook.com/me/friends). The names will be exactly as they appear there.

**Comment by NoLooseEnds** [comment]
No, thats the thing. The two fb friends I have issues with does _not_ show up in the list.

They do show up in the link you just posted (mbasic.facebook.com). And I have full access to their account as normal – ie. see photos, wall, etc.

**Comment by pkoenig10** [comment]
If they show up on the website, they should be in the list. You can try adding print statements to the scraping to see where things are going wrong.

**Comment by NoLooseEnds** [comment]
Thanks. I think I found the correct place (line 137?) in sink.py, but what do I enter there get it to print? I tried "print get_friends", but that did not work.

Sorry, but I got little knowledge of phyton. I tried looking at pdb, but did not get that to output anything  log-like either.

**Comment by pkoenig10** [comment]
The key bit of the scraping code is done here:
https://github.com/pkoenig10/sink/blob/master/sink.py#L126-L136

pdb is probably overkill for this - adding some temporary print statements should be sufficient.

May I suggest spending a little bit of time learning python? It will be easier to solve this problem if you understand what the code is doing and can do the debugging yourself. There is only so much help I can provide because the data is coming from your Facebook account.

**Comment by NoLooseEnds** [comment]
Thanks, I'll see what I can dig out.

Yes, that is probably the ideal thing, but it's not going to happen right now at least (because of life/priorities). But python is probably a good language to learn.

If I'm being honest, the only reason for this is that I moved contacts from one account to another, and lost all the images in the process. I found your great script, and that worked great except for the two issues (crashing on unicode and the two friends that does not show). The first one you fixed super fast. I could just update the last two manually, but I figured I would give this a go – if it's a relatively easy fix. :)

I'll report back if I manage to get it to print an output and see anything weird.

**Comment by NoLooseEnds** [comment]
Ok, I managed to output the raw HTML, but I do not find the two friends in question. So I'm guessing the script is parsing everything just right.

The issue is: Why don't they show up? I can find them fine if I search on in the searchbar on the mobile site.

As I have mentioned I can see them just fine in the browser. All photos, wall posts, etc.

Have you experienced that before?

**Comment by pkoenig10** [comment]
Are you saying that they show up in the friends list on the normal Facebook site (https://www.facebook.com) but not the paginated friends list on the mbasic site?

I'm not sure why there would be a discrepancy, but if that is the case there isn't really anything I can do. That's an issue with Facebook.

**Comment by NoLooseEnds** [comment]
Correct, and I can search them up without a problem. The issues seems to be with Facebook, but it's weird. 

Thanks for your help, much appreciated. I'll let you know if I figure it out :)
