### ISSUE TITLE
only finding silhouette images

### ISSUE THREAD

**Issue by buck2202** [pkoenig10/sink#12]
Facebook seems to have broken this. Digging through your urls and applying Zuckerberg's ID (4)

response to `https://graph.facebook.com/4/picture?height=720&width=720&redirect=false`
is 
```
{
   "data": {
      "height": 720,
      "is_silhouette": true,
      "url": "https://scontent.xx.fbcdn.net/v/t31.0-1/c212.0.720.720/p720x720/10733713_10150004552801937_4553731092814901385_o.jpg?_nc_cat=0&oh=887e250445f6a644b04e695932970303&oe=5B68D1F0",
      "width": 720
   }
}
```
and following the URL just gets the silhouette.

This broke a bunch of Play Store apps for syncing FB profile photos as well.

**Comment by buck2202** [comment]
Maybe a transient issue, or maybe a security change. Doesn't seem to be a clear answer from facebook yet

https://developers.facebook.com/bugs/185053568795519
https://developers.facebook.com/bugs/2054375031451090/

**Comment by pkoenig10** [comment]
Seems to have been fixed. Others are indicating that in the bug comments and I am getting a non-silhouette response response when I try to get Zuckerberg profile picture.

@buck2202 can you confirm that it is working again for you?

**Comment by buck2202** [comment]
Confirmed.

I'm having a separate issue that my pulled friend list seems to be incomplete, but I'm a new user so I'm not sure if it's related/new or not. Might create a new issue after some checking on my end. Thanks for your work! I like the idea of this code better than the semi-automatic play store apps.

**Comment by pkoenig10** [comment]
Was seeing a similar issue with incomplete friends lists in #10. It seems there was a discrepancy between the normal desktop site and the basic mobile site used to scrape your friends list.
