### ISSUE TITLE
Platform?

### ISSUE THREAD

**Issue by Tyree** [pkoenig10/sink#13]
Sorry, this isn't really an "issue." It's just my ignorance of how to use your software. What platform is this meant to be used on? I see you're using python. Can I implement this from a Windows PC? This sounds like exactly what I'm looking for. I want the ability to use the Facebook profile photos on my Google contacts without involving my phone. Is this possible?

Thanks!

**Comment by Tyree** [comment]
I installed Python for Windows. Ran the initial setup command and I got:
```
PS M:\> python setup.py
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    install()
  File "setup.py", line 6, in install
    pip.main(['install', 'beautifulsoup4', 'gdata', 'fuzzywuzzy'])
AttributeError: module 'pip' has no attribute 'main'
PS M:\> pkoenig10/sink
```

**Comment by Tyree** [comment]
Update to the pip problem. I had to downgrade from v 10.0.1 to 9.0.3. V10 doesn't support main.

That allowed me to download and install the dependencies. Now there's a new issue:
```
PS M:\> python sink.py update
  File "sink.py", line 102
    print "Incorrect login. Try again."
                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Incorrect login. Try again.")?
```

**Comment by Tyree** [comment]
Added parens to all print commands. Now this...
```
PS M:\> python sink.py update
Traceback (most recent call last):
  File "sink.py", line 9, in <module>
    import cookielib
ModuleNotFoundError: No module named 'cookielib'
```
Little too buggy for this noob. :-)

**Comment by pkoenig10** [comment]
This module was renamed to `cookiejar` in Python 3. I need to update this repo to work with Python 3.

It should work using Python 2.

**Comment by Tyree** [comment]
Gotcha. I'll keep watch for the Python 3 update.
Thanks!

**Comment by pkoenig10** [comment]
This repo has been updated to use Python 3.
