### ISSUE TITLE
error with python3

### ISSUE THREAD

**Issue by Flavien06** [pkoenig10/sink#16]
Hi,
I have this error
any ideas?

```
Traceback (most recent call last):
  File "sink.py", line 427, in <module>
    main()
  File "sink.py", line 386, in main
    args = parse_args()
  File "sink.py", line 398, in parse_args
    subparsers = parser.add_subparsers(dest='command', metavar='command', required=True)
  File "/usr/lib/python3.5/argparse.py", line 1708, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```

**Comment by pkoenig10** [comment]
The `add_subparsers` command didn't support the `required` option until Python 3.7. See https://github.com/python/cpython/pull/3027.

Upgrading to Python 3.7 or later should resolve the issue.

**Comment by Flavien06** [comment]
Ok thank.
But does not works with two-factor authentication

**Comment by Flavien06** [comment]
thank
but not works with two-factor authentication even when using a app password.

**Comment by pkoenig10** [comment]
Adding support for two-factor authentication is difficult because logging in is done by scraping the mbasic webpage.

If you would like support for two-factor authentication can you please open a new issue?
