### ISSUE TITLE
Change to API?

### ISSUE THREAD

**Issue by Tyree** [pkoenig10/sink#21]
Seems like Sink is choking on my Facebook login. Keeps saying it's wrong, but I haven't changed anything. Repeated attempts to enter the login info and it still says it's wrong. Makes me think perhaps FB changed their API. Any thoughts?

Thanks!

**Comment by pkoenig10** [comment]
Looks like they changed the path for the logged in home page from `/home.php` to just `/`. So you were logging in correctly but Sink thought you weren't logged in since the path had changes. Fix is in #22.

Thanks for opening an issue!

**Comment by Tyree** [comment]
Thanks!
