### ISSUE TITLE
Gracefully handle rate limiting

### ISSUE THREAD

**Issue by Mxbonn** [pkoenig10/sink#27]
I keep getting this error.
Authorizing google and facebook works fine but it fails when actually trying to update the photos.
````
Authorizing Google...
Getting Google contacts...
[RETRACTED]  contacts
Authorizing Facebook...
Facebook two-factor authentication code: [RETRACTED]
Getting Facebook friends...
[RETRACTED] friends
Updating links...
Updating photos...
Traceback (most recent call last):
  File "sink.py", line 451, in <module>
    main()
  File "sink.py", line 414, in main
    sink.update(args.update_ignored, args.auto_only, args.score_threshold, args.match_limit, args.retries)
  File "sink.py", line 268, in update
    self._update_photos(retries)
  File "sink.py", line 283, in _update_photos
    picture = self.facebook.get_profile_picture(friend_url, self.friends[friend_url])
  File "sink.py", line 164, in get_profile_picture
    user_id = re.search(self.user_id_regex, profile_response.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
````

**Comment by pkoenig10** [comment]
I just pulled the latest from the `master` branch and it seems to work correctly for me.

The user ID is scraped from the "Messages" link on a user's profile link, which can be found at `https://mbasic.facebook.com/<user-id>`. For example:

<img width="451" src="https://user-images.githubusercontent.com/5273164/64480871-695bf300-d185-11e9-9ec2-117b5c1ac30b.png">

The easiest way to debug this would be to navigate to the page of the user that is failing and inspect the page to see why the messages link is not found.

**Comment by pkoenig10** [comment]
It looks like Facebook has implemented some rate-limiting. The page when the user ID is not found looks like:

![](https://user-images.githubusercontent.com/5273164/64480950-54805f00-d187-11e9-980c-9c2b24219714.png)

**Comment by PercevalSA** [comment]
Hello @Mxbonn, 
I encountered the same problem so I patched Sink to handle blocking by Facebook and resume after block detection. However, you have to re-run the script manually and wait between two runs for the blocking to disappear. You can find the patch:

- in my pull request: https://github.com/pkoenig10/sink/pull/28 

- in my repo : https://github.com/percevalsa/sink
