### ISSUE TITLE
Error when trying to use Google Authentication

### ISSUE THREAD

**Issue by akyriacou** [pkoenig10/sink#32]
Tried multiple times to go through the Google Authentication but OAuth keeps failing due to no client_id.

Noticed this in the code:

    client_id = os.getenv('SINK_CLIENT_ID')
    client_secret = os.getenv('SINK_CLIENT_SECRET')

What values should these be?

Thank you

**Comment by pkoenig10** [comment]
You need to obtain OAuth2 credentials and use those when running the script. See the Google documentation:
https://developers.google.com/identity/protocols/oauth2#1.-obtain-oauth-2.0-credentials-from-the-dynamic_data.setvar.console_name-.
