### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

### ISSUE THREAD

**Issue by rubenverhoef** [pkoenig10/sink#7]
I'm getting the following error when doing `python sink.py update`.
I'm using Python 2.7.14

`Traceback (most recent call last):
  File "sink.py", line 433, in <module>
    main()
  File "sink.py", line 394, in main
    sink = Sink(shelf)
  File "sink.py", line 246, in __init__
    self.friends = self.facebook.get_friends()
  File "sink.py", line 127, in get_friends
    friends_base_path = self.get_profile_path() + '/friends'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

**Comment by pkoenig10** [comment]
Looks like the HTML parser can't find the "Profile" link:
https://github.com/pkoenig10/sink/blob/3c21f0769ed643e371fb7420824aa32d3dde4fb6/sink.py#L120-L123


Easiest way to debug this is to go to https://mbasic.facebook.com. It should look like a basic version of the mobile website. If you open developer tools and inspect the page, you should see a link tag whose contents are "Profile". The href for that link should be something like `"/<your_username>?<query_string>"`.

For example, you should see something like this:
![screenshot from 2018-01-06 15-49-03](https://user-images.githubusercontent.com/5273164/34645064-460c8994-f2f9-11e7-8307-28ede4cd38cf.png)

**Comment by rubenverhoef** [comment]
Yeah! that was it, my Facebook was in a different language. I changed my Facebook to English and it is working!
